name: Unit Tests
on:
  push:
    branches:
      - master
      - 'v3.[0-9]+'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test -v ./...
